[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite', 'UniteWithCursorWord']

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'cocopon/iceberg.vim'
  hook_add = '''
  autocmd MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoList', 'MemoNew']
hook_source = '''
  let g:memolist_memo_suffix = 'md'
  let g:memolist_filename_prefix_none = 1
  let g:memolist_unite = 1
  let g:memolist_unite_option = '-buffer-name=files'
'''

[[plugins]]
repo = 'https://github.com/kana/vim-metarw'

[[plugins]]
repo = 'mattn/webapi-vim'
