hook_add = '''
function! SourceMyRC(rc_file) abort
  let path = fnamemodify($MYVIMRC, ':h') . '/plugins/' . a:rc_file
  execute 'source ' . path
endfunction
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite', 'UniteWithCursorWord', 'UniteWithBufferDir']
hook_source = 'call SourceMyRC("unite.rc.vim")'

[[plugins]]
if = "has('python3') && has('nvim')"
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'call SourceMyRC("denite.rc.vim")'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
on_source = 'denite.nvim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'l04m33/vlime'
on_ft = 'lisp'
rtp = 'vim'
hook_source = 'call SourceMyRC("vlime.rc.vim")'

[[plugins]]
repo = 'cocopon/iceberg.vim'
  hook_add = '''
  autocmd MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoList', 'MemoNew']
hook_source = 'call SourceMyRC("memolist.rc.vim")'

[[plugins]]
repo = 'w0rp/ale'
on_cmd = ['ALELint', 'ALEToggle', 'ALEEnable', 'ALEToggleBuffer', 'ALEEnableBuffer']
hook_source = 'call SourceMyRC("ale.rc.vim")'

[[plugins]]
repo = 'janko-m/vim-test'
on_cmd = ['TestNearest', 'TestFile', 'TestSuite', 'TestLast', 'TestVisit']
hook_source = 'call SourceMyRC("vim-test.rc.vim")'
