[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
on_source = ['unite.vim', 'vimshell.vim']
hook_post_update = '''
  if has('win32') || has('win64')
    !tools\\update-dll-mingw
  elseif has('win32unix') 
    !make -f make_cygwin.mak
  elseif executable('gmake')
    !gmake
  else
    !make
  endif
'''
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_cmd = ['VimShell', 'VimShellTab', 'VimShellExecute', 'VimShellInteractive']
depends = 'vimproc.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
if = "has('python3')"
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = 'unite.vim'
hook_source = '''
	call denite#custom#map(
	  \ 'insert',
	  \ '<C-j>',
	  \ '<denite:move_to_next_line>',
	  \ 'noremap'
	  \)
	call denite#custom#map(
	  \ 'insert',
	  \ '<C-p>',
	  \ '<denite:move_to_previous_line>',
	  \ 'noremap'
	  \)
'''

