hook_add = '''
function! SourceMyRC(rc_file) abort
  let path = fnamemodify($MYVIMRC, ':h') . '/plugins/' . a:rc_file
  execute 'source ' . path
endfunction
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'vlime/vlime'
on_ft = 'lisp'
rtp = 'vim'
hook_source = 'call SourceMyRC("vlime.rc.vim")'

[[plugins]]
repo = 'cocopon/iceberg.vim'
  hook_add = '''
  autocmd MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'dense-analysis/ale'
on_cmd = ['ALELint', 'ALEToggle', 'ALEEnable', 'ALEToggleBuffer', 'ALEEnableBuffer']
on_func = 'ale#completion#OmniFunc'
hook_source = 'call SourceMyRC("ale.rc.vim")'
depends = 'asyncomplete.vim'
on_source = 'asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_func = 'asyncomplete#enable_for_buffer'
hook_source = 'call SourceMyRC("asyncomplete.rc.vim")'

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_cmd = ['EditorConfigEnable', 'EditorConfigReload']
