hook_add = '''
function! SourceMyRC(rc_file) abort
  let path = fnamemodify($MYVIMRC, ':h') . '/plugins/' . a:rc_file
  execute 'source ' . path
endfunction
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
on_source = 'unite.vim'
hook_add = '''
let s:is_windows = has("win32") || has("win64")
let g:vimproc#download_windows_dll = s:is_windows
if !s:is_windows
  let g:dein#plugin.build = 'make'
endif
'''
hook_post_update = '''
if !g:vimproc#download_windows_dll
  call dein#build('vimproc.vim')
endif
'''

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite', 'UniteWithCursorWord', 'UniteWithBufferDir']
hook_source = 'call SourceMyRC("unite.rc.vim")'

[[plugins]]
if = "has('python3') && has('nvim')"
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'call SourceMyRC("denite.rc.vim")'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'l04m33/vlime'
on_ft = 'lisp'
rtp = 'vim'
hook_source = 'call SourceMyRC("vlime.rc.vim")'

[[plugins]]
repo = 'cocopon/iceberg.vim'
  hook_add = '''
  autocmd MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoList', 'MemoNew']
hook_source = 'call SourceMyRC("memolist.rc.vim")'

[[plugins]]
repo = 'dense-analysis/ale'
on_cmd = ['ALELint', 'ALEToggle', 'ALEEnable', 'ALEToggleBuffer', 'ALEEnableBuffer']
on_func = 'ale#completion#OmniFunc'
hook_source = 'call SourceMyRC("ale.rc.vim")'
depends = 'asyncomplete.vim'

[[plugins]]
repo = 'benmills/vimux'
on_func = ['VimuxRunCommand', 'VimuxOpenRunner']
hook_source = 'let g:VimuxUseNearest = 0'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_func = 'asyncomplete#enable_for_buffer'
hook_source = 'call SourceMyRC("asyncomplete.rc.vim")'

[[plugins]]
repo = 'yami-beta/asyncomplete-omni.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_source = 'call SourceMyRC("quickrun.rc.vim")'
