hook_add = '''
function! SourceMyRC(rc_file) abort
  let path = fnamemodify($MYVIMRC, ':h') . '/plugins/' . a:rc_file
  execute 'source ' . path
endfunction
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'vlime/vlime'
on_ft = 'lisp'
rtp = 'vim'
hook_source = 'call SourceMyRC("vlime.rc.vim")'

[[plugins]]
repo = 'uki00a/vim-deno'
on_cmd = ['DenoFmt', 'DenoDoc', 'DenoTest']
build = 'npm install'

[[plugins]]
repo = 'cocopon/iceberg.vim'
  hook_add = '''
  autocmd MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_func = 'lsp#enable'
depends = 'vim-deno'

[[plugins]]
repo = 'dense-analysis/ale'
on_cmd = ['ALEFix', 'ALEFixSuggest', 'ALELint', 'ALEToggle', 'ALEEnable', 'ALEToggleBuffer', 'ALEEnableBuffer']
on_func = 'ale#completion#OmniFunc'
hook_source = 'call SourceMyRC("ale.rc.vim")'
depends = ['asyncomplete.vim', 'vim-deno']
on_source = 'asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_func = 'asyncomplete#enable_for_buffer'
hook_source = 'call SourceMyRC("asyncomplete.rc.vim")'
depends = ['vlime']

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'

[[plugins]]
repo = 'junegunn/fzf'
on_source = 'fzf.vim'
hook_post_update = "call fzf#install()"

[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = ['FzfFiles', 'FzfBuffers', 'FzfLines', 'FzfAg', 'FzfHistory:']
on_func = ['fzf#run', 'fzf#wrap']
depends = ['fzf']
hook_add = '''
let g:fzf_command_prefix = "Fzf"
'''
hook_source = 'call SourceMyRC("fzf.rc.vim")'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_cmd = ['EditorConfigEnable', 'EditorConfigReload']
